### ISSUE TITLE
Unable to Run the example

### ISSUE THREAD

**Issue by sbudoff** [qyyin0516/CellTICS#1]
Hi,
I recieve the following error when running your example script and example data:

```
$ python -u code/main.py -dataset_name 'L5MB'                             -reference_data_path 'example_data/L5MB_rdata.csv'                             -query_data_path 'example_data/L5MB_qdata.csv'                             -reference_label_path 'example_data/L5MB_rlabel.csv'                             -ensembl_pathway_relation 'reactome/Ensembl2Reactome_All_Levels.txt'                             -pathway_names 'reactome/ReactomePathways.txt'                             -pathway_relation 'reactome/ReactomePathwaysRelation.txt'
2024-01-28 13:49:36.796647: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-28 13:49:36.817761: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-28 13:49:36.817784: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-28 13:49:36.818344: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-28 13:49:36.821750: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-28 13:49:37.206933: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/XXXX/anaconda3/envs/XXXX/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

Traceback (most recent call last):
  File "/home/XXXX/XXXX/XXXX/CellTICS/code/main.py", line 183, in <module>
    main()
  File "/home/XXXX/XXXX/XXXX/CellTICS/code/main.py", line 58, in main
    pathway_genes = get_gene_pathways(args.ensembl_pathway_relation, species=args.species)
  File "/home/XXXX/XXXX/XXXX/CellTICS/code/pathway_hierarchy.py", line 18, in get_gene_pathways
    ensembl.columns = ['gene', 'group']
  File "/home/XXXX/anaconda3/envs/XXXX/lib/python3.9/site-packages/pandas/core/generic.py", line 5478, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/home/XXXX/anaconda3/envs/XXXX/lib/python3.9/site-packages/pandas/core/generic.py", line 670, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/XXXX/anaconda3/envs/XXXX/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 220, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements

```
I am running this on Ubuntu 22.04, in a freshly created conda enviorment with the dependencies you instructed. The issue is coming from the `get_gene_pathways` function so wanted to let you all know.

Good luck!

**Comment by qyyin0516** [comment]
Hi there,

Thanks for your question. This is because of the file Ensembl2Reactome_All_Levels.txt.

CellTICS/reactome/Ensembl2Reactome_All_Levels.txt and CellTICS/example_data/example_data.zip are stored with Git LFS because they are larger than 25MB. Please download the two files directly via the github page. After downloading them, please put Ensembl2Reactome_All_Levels.txt to CellTICS/reactome. Then it should work.

Sorry for any inconvenience.

**Comment by sbudoff** [comment]
That worked! Thank you for the quick response and easy fix.
